### PR TITLE
Adding Terminology across the DI/1 documentation

### PR DESCRIPTION
**Pull request by cybersonic**
This adds definitions of which the rest of the document can work from.

### CODE REVIEW

**Comment by seancorfield** [comment]
:+1:

**Comment by seancorfield** [comment]
The site has been regenerated with these changes and deployed to production!

**Comment by cybersonic** [comment]
Looks like the formatting of the terminology section has gone out of the window. I tried to test it but Jekyll is giving errors on this. 

Will re-format and submit. 

MD

**Comment by seancorfield** [comment]
I don't even see that section on the generated page. Odd. Just the TOC entry.

I'll double-check the next PR locally before I deploy. Look forward to your updates.

**Comment by cybersonic** [comment]
Jekyll wasn’t playing nice with some plugins and refusing to run so I couldn’t preview. I have made the changes now and they should be showing up nicely locally.

**Pull request merged**
