### PR TITLE
Cfsimplicity patch 1

### PR DESCRIPTION
**Pull request by cfsimplicity**
Add note that requirement for lower case filenames only applies to case-senstive OSes.

### CODE REVIEW

**Comment by seancorfield** [comment]
You need to send the PR against the source Markdown not the generated HTML.

**Comment by cfsimplicity** [comment]
How do I do that? I'm not seeing any Markdown in the repo, only HTML.

**Comment by cfsimplicity** [comment]
Ah, I've found the Markdown. New PR coming up.

**Comment by seancorfield** [comment]
The `source` branch. That's how Jekyll sites are built. I'll see if I can figure out how to add a `README.md` and `CONTRIBUTING.md` to the generated HTML `master` branch but the update / deploy is all automated so I'm not sure that's possible... I could just update the repo description I guess...

**Comment by cfsimplicity** [comment]
Don't worry Sean I think I've found out how to edit the MD directly and submit as a PR.

**Pull request closed without merging**
